spring:
  application:
    name: pass-batch
  datasource:                           # docker-compose? ???? DB ?? ?????.
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:                             # Spring Boot2?? default DBCP? hikariCP???.
      maximum-pool-size: 20             # pool? ?? ??? ?? connection ?
      # minimum-idle: 20                  maximum-pool-size? ????? ??? ?????.
  batch:
#    job:
#      enabled: false # ??? true? Spring Boot ?? ? ???? ?? Job?? ?????.
    jdbc:
      # Batch? ???? SQL ??? ????? ?????. ????? ???? ????? ?????, always ??? ?? ???? ???? ?? ????? ? ????.
      # ?? ??? ???? ???? ???.
      initialize-schema: always

kakaotalk:
  host: https://kapi.kakao.com
  token: YOUR_ACCESS_TOKEN